import { AskResponse, SourceMatch } from "@/lib/types";

const templates: Array<{ keys: RegExp; questions: string[] }> = [
  { keys: /(drag|free fall|projectile|terminal velocity)/i, questions: ["What forces are acting on the object, and which of them changes with velocity?", "If the object speeds up, what happens to the drag force relative to gravity?", "What would have to be true for the acceleration to shrink toward zero?"] },
  { keys: /(pendulum|oscillation|harmonic|damping)/i, questions: ["When the system is displaced, what pulls it back toward equilibrium?", "How does the restoring effect depend on the size of the displacement?", "If damping or driving is present, where is the system losing or gaining energy?"] },
  { keys: /(orbit|gravitation|kepler|centripetal)/i, questions: ["If an object moves closer to the central mass, how does the gravitational force change?", "What kind of acceleration is needed to keep the object curving instead of moving in a straight line?", "How should speed and distance relate if the object is to remain in orbit?"] },
  { keys: /(chaos|chaotic|sensitive)/i, questions: ["If two simulations start with almost identical initial conditions, do they stay close forever?", "What would it mean physically if tiny differences grow rapidly over time?", "How can a deterministic rule still produce behavior that appears unpredictable?"] },
  { keys: /(random walk|diffusion|probability|stochastic)/i, questions: ["What part of the process is random, and what quantity are we tracking over many trials?", "Even if one path is unpredictable, what average pattern might emerge over many paths?", "Why might a distribution or mean-square displacement be more useful than a single trajectory?"] },
  { keys: /(molecular dynamics|particle simulation)/i, questions: ["What microscopic rule determines how one particle pushes or pulls on another?", "If many particles interact at once, what macroscopic quantities could emerge?", "Why do time step size and boundary conditions matter for believable simulations?"] },
  { keys: /(fourier|wave|mode|frequency)/i, questions: ["What pattern in space or time are we trying to decompose?", "Which frequencies or modes would contribute most strongly?", "How does thinking in modes make the system easier to analyze?"] },
  { keys: /(electric field|potential|electrostatic|poisson)/i, questions: ["Which quantity is easier to solve for first: the field or the potential?", "How do charges or boundary values constrain the solution?", "Once the potential is known, how can the field or force be recovered?"] },
  { keys: /(monte carlo|statistical mechanics|partition function)/i, questions: ["What are the possible states of the system, and how are they sampled?", "Why does random sampling help when summing over every configuration is too expensive?", "What observable would show whether the system is approaching equilibrium or changing phase?"] },
  { keys: /(differential equation|numerical|euler|runge|ode|pde)/i, questions: ["If we know the rate of change now, how could we estimate the next value a short time later?", "What role does step size play in balancing speed and accuracy?", "Why can repeated small updates approximate a full continuous solution?"] }
];

const stopWords = new Set(["the", "is", "a", "an", "and", "to", "of", "in", "for", "on", "with", "why", "how", "does"]);
export const extractKeywords = (query: string, maxTerms = 6): string[] => Array.from(new Set(query.toLowerCase().replace(/[^a-z0-9\s]/g, "").split(/\s+/).filter(w => w.length > 2 && !stopWords.has(w)))).slice(0, maxTerms);
export const splitSentences = (text: string): string[] => text.split(/(?<=[.!?])\s+/).map(s => s.trim()).filter(Boolean);
export function bestSupportSentences(context: string, query: string, k = 3): string[] { const keys = extractKeywords(query); return splitSentences(context).map(s => ({ s, sc: keys.reduce((a, kw) => a + (s.toLowerCase().includes(kw) ? 1 : 0), 0) })).sort((a,b)=>b.sc-a.sc).slice(0,k).map(x=>x.s); }
export const conceptLabel = (query: string, supportSentences: string[]): string => extractKeywords(`${query} ${supportSentences.join(" ")}`, 2).join(" + ") || "core physics principle";
export function buildSocraticQuestions(query: string, supportSentences: string[]): string[] { const hay = `${query} ${supportSentences.join(" ")}`; return templates.find(t => t.keys.test(hay))?.questions ?? ["What are the main physical quantities in this question?", "If one of those quantities increases, what would you expect to happen to the others?", "Which physical principle links those quantities together?"]; }
export function buildTutorResponse(question: string, matches: SourceMatch[]): AskResponse { const context = matches.map(m => m.text).join(" "); const support = bestSupportSentences(context, question, 3); return { question, socraticQuestions: buildSocraticQuestions(question, support), hint: { supportSentences: support.slice(0,2) }, takeaway: `Focus on ${conceptLabel(question, support)} and explain how the relationships change step-by-step.`, sources: matches }; }
